sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
    directories:
      - node_modules
language: node_js
node_js:
    - "7"
before_install:
    - "node --version"
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
services:
    - mongodb
env:
    - ENV_OPTS=0
    - PHANTOMJS_BIN=./node_modules/.bin/phantomjs
group: deprecated-2017Q2
os: linux
